package vn.teko.cart.domain.constants

const val SELLER_ID_PHONGVU = 1
const val SELLER_ID_VNSHOP = 2
const val SELLER_ID_VINMART = 4

const val SHIPPING_FEE_PHONGVU = 11_000.0
const val SHIPPING_FEE_VNSHOP = 0.0
const val SHIPPING_FEE_VINMART = 29_000.0

const val SHIPPING_SKU_PHONGVU = "1206838"
const val SHIPPING_SKU_VINMART = "VMA00001"

const val SHIPPING_ITEM_NAME_PHONGVU = "Phí dịch vụ giao hàng tận nơi"
const val SHIPPING_ITEM_NAME_VINMART = "Phí dịch vụ giao hàng tận nơi"

const val FREE_SHIPPING_MILESTONE_PHONGVU = 500_000.0
const val FREE_SHIPPING_MILESTONE_VNSHOP = 0.0
const val FREE_SHIPPING_MILESTONE_VINMART = 100_000_000_000.0

const val TECHNICAL_SUPPORT_FEE_PHONGVU = 55_000.0

const val FREE_TECHNICAL_SUPPORT_MILESTONE_PHONGVU = 5_000_000.0

const val SHIPPING_AND_TECHNICAL_SUPPORT_NAME_PHONGVU =
    "Phí dịch vụ giao hàng tận nơi+hỗ trợ kỹ thuật"

const val SHIPPING_AND_TECHNICAL_SUPPORT_SKU_PHONGVU = "1702079"
